version: '3.8'

services:
  metricbeat:
    image: beats/metricbeat:${VERSION}
    container_name: metricbeat
    network_mode: host
    env_file: .env
    command: ["--strict.perms=false", "-system.hostfs=/hostfs", "-e"]
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - certs:$CERTS_DIR
      - ./configs/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./configs/modules.d:/usr/share/metricbeat/modules.d:ro

      # system module
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro

      # docker module
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  certs:
    external: true
    name: elastic-stack-certs
