metricbeat.config:
  modules:
    path: ./modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

setup.kibana:
  host: "${KIBANA_HOST:10.1.19.1:9201}"
  protocol: "https"
  username: "metricbeat_setup"
  password: "${METRICBEAT_SETUP_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["${CERTS_DIR}/ca/ca.crt"]
    verification_mode: "certificate"

setup.dashboards.enbaled: false

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOST:localhost:9200}'
  protocol: "https"
  username: 'metricbeat_writer'
  password: '${METRICBEAT_WRITER_PASSWORD}'
  ssl:
    certificate_authorities: ["${CERTS_DIR}/kibana/elasticsearch-ca.pem"]
    verification_mode: "certificate"
